name: dockerizedjs-workflow
run-name: ${{github.actor}} is running dockerizedjs-action
on:
  workflow_dispatch
jobs:
  dockerizedjs-job:
    runs-on: ubuntu-latest
    steps:
      #- uses: MarkTurney/d-checkout@v1.0.0
      - uses: AndriiChyrva/d-checkout@v1.0.0
      #- uses: AndriiChyrva/dockerizedjs-action@v1.0